name: CI
on:
    workflow_dispatch:
        push:
            branches:
                - master
        pull_request:

env:
    HUSKY: 0

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: nrwl/nx-set-shas@v3
            - run: npm ci

            - run: npx nx format:check
            - run: npx nx affected -t lint --parallel=3
            - run: npx nx affected -t test --parallel=3 --configuration=ci
            - run: npx nx affected -t build --parallel=3

            - name: Release
              if: ${{ success() && (github.event_name != 'pull_request' || github.event.action == 'closed' && github.event.pull_request.merged == true) }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npx nx run-many --target release --all

            - name: Create Release
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\///')
                  echo "Creating release for tag $tag"
                  affected_projects=$(npx nx affected:apps --base=${{ github.event.before }} --head=${{ github.event.after }} --plain)
                  for project in $affected_projects; do
                    release_notes=$(sed -n "/## \[$tag\]/,/^##/p" $project/changelog.md)
                    gh release create "$tag-$project" --title "$tag-$project" --notes "$release_notes"
                  done
